[package]
name = "owg-persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
owg-protocol = { path = "../owg-protocol" }
anyhow = { workspace = true }
